[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
elowen = "48ug74S2RBzih8DtNpyDqhTCZnzUoYuYyzwttmHEiMRS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
burn-listen = "ts-node tests/burn-listen.ts"
create-alt = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/create-alt.spec.ts"
data = "find tests -name \"*.ts\" | grep -v \".spec.ts\" | grep -vE \"listen.ts$\" | grep -vE \"common.ts$\" | xargs -I {} ts-node {}"
eda-withdraw = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/eda/withdraw.spec.ts"
initialize-elw = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize-elw.spec.ts"
liquidity-collect = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/liquidity/collect.spec.ts"
liquidity-deposit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/liquidity/deposit.spec.ts"
liquidity-get-amounts = "ts-node tests/liquidity/get-amounts.ts"
liquidity-get-fees = "ts-node tests/liquidity/get-fees.ts"
liquidity-get-price = "ts-node tests/liquidity/get-price.ts"
liquidity-initialize = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/liquidity/initialize.spec.ts"
liquidity-locked-lp-info = "ts-node tests/liquidity/locked-lp-info.ts"
liquidity-locked-lp-state = "ts-node tests/liquidity/locked-lp-state.ts"
liquidity-mining-claim = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/liquidity/mining/claim.spec.ts"
liquidity-mining-deposit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/liquidity/mining/deposit.spec.ts"
liquidity-mining-lp-vaults = "ts-node tests/liquidity/mining/lp-vaults.ts"
liquidity-mining-sol-state = "ts-node tests/liquidity/mining/sol-state.ts"
liquidity-mining-usdc-state = "ts-node tests/liquidity/mining/usdc-state.ts"
liquidity-mining-withdraw = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/liquidity/mining/withdraw.spec.ts"
liquidity-pool-info = "ts-node tests/liquidity/pool-info.ts"
liquidity-ray-nfts = "ts-node tests/liquidity/ray-nfts.ts"
liquidity-state = "ts-node tests/liquidity/state.ts"
liquidity-swap-sol = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/liquidity/swap-sol.spec.ts"
liquidity-swap-usdc = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/liquidity/swap-usdc.spec.ts"
liquidity-unwrap-wsol = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/liquidity/unwrap-wsol.spec.ts"
liquidity-vault-swap = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/liquidity/vault-swap.spec.ts"
platform-burn = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/platform/burn.spec.ts"
platform-vaults = "ts-node tests/platform/vaults.ts"
platform-withdraw = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/platform/withdraw.spec.ts"
premium-buy = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/premium/buy.spec.ts"
premium-listen = "ts-node tests/premium/listen.ts"
premium-withdraw = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/premium/withdraw.spec.ts"
presale-account = "ts-node tests/presale/account.ts"
presale-burn = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/presale/burn.spec.ts"
presale-buy = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/presale/buy.spec.ts"
presale-claim = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/presale/claim.spec.ts"
presale-listen = "ts-node tests/presale/listen.ts"
presale-summary = "ts-node tests/presale/summary.ts"
reward-account = "ts-node tests/reward/account.ts"
reward-claim = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/reward/claim.spec.ts"
reward-listen = "ts-node tests/reward/listen.ts"
team-account = "ts-node tests/team/account.ts"
team-claim = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/team/claim.spec.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.spec.ts"
transaction-listen = "ts-node tests/transaction-listen.ts"
transactions = "ts-node tests/transactions.ts"
user-balances = "ts-node tests/user-balances.ts"
vault-balances = "ts-node tests/vault-balances.ts"
