[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
elowen = "3R63fNvrbn2mb2Em28i4UTPEJN83EAVQDmFuNzrkXVKw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
create-alt = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/create-alt.spec.ts"
initialize-elw = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize-elw.spec.ts"
eda-withdraw = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/eda/withdraw.spec.ts"
platform-burn = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/platform/burn.spec.ts"
platform-vaults = "ts-node tests/platform/vaults.ts"
platform-withdraw = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/platform/withdraw.spec.ts"
team-account = "ts-node tests/team/account.ts"
team-claim = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/team/claim.spec.ts"
reward-account = "ts-node tests/reward/account.ts"
reward-claim = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/reward/claim.spec.ts"
reward-listen = "ts-node tests/reward/listen.ts"
presale-account = "ts-node tests/presale/account.ts"
presale-burn = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/presale/burn.spec.ts"
presale-buy = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/presale/buy.spec.ts"
presale-claim = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/presale/claim.spec.ts"
presale-listen = "ts-node tests/presale/listen.ts"
presale-summary = "ts-node tests/presale/summary.ts"
premium-buy = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/premium/buy.spec.ts"
premium-listen = "ts-node tests/premium/listen.ts"
premium-withdraw = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/premium/withdraw.spec.ts"